### ISSUE TITLE
Materials in xacro aren't seen in gazebo

### ISSUE THREAD

**Issue by eugene-katsevman** [MobileRobots/amr-ros-config#7]
Since sdformat has a bug 

https://bitbucket.org/osrf/sdformat/issues/132/parser-does-not-handle-urdf-material

and xacros has "base_visual" name for all the visuals, models are gray in gazebo with no applied materials.

**Comment by reed-adept** [comment]
Thanks.   Can we just remove the name attribute on the visual elements then?   Will have to just check if that’s used in the URDF files for something.

**Comment by eugene-katsevman** [comment]
Yes, you can. I've tried it and it works. Actually your project has a fork with that issue been dealt in its latest commit.
Or I can prepare a pull request

**Comment by eugene-katsevman** [comment]
Here is the fork
https://github.com/thpe/amr-ros-config/network

**Comment by reedhedges** [comment]
Thanks for finding that.  Yes I could merge his fork (See PR #8) if that's ok with Thomas and there are no comments or objections about it, then take a look and see if the off-center issues etc. can be fixed.  If anyone fixes them in the mean time please let us know here or via PR.

**Comment by reed-adept** [comment]
Thanks for finding that. Yes I could merge his fork (See PR #8) if that's ok with Thomas and there are no comments or objections about it, then take a look and see if the off-center issues etc. can be fixed. If anyone fixes them in the mean time please let us know here or via PR.
